@startuml

class 病人 {
}

class 挂号单 {
}
挂号单 }-l- 病人

class 入院单 {
    入院日期时间
}

入院单 }-up- 挂号单
入院单 }-up- 病人

class 病房 {
    价格
}

class 病床 {
}

病床 }-- 病房

class 管床护士 {
}

管床护士 --{ 病房

class 住院记录 {
    入院日期时间
    出院日期时间
    状态
    总费用
}
住院记录 -- 入院单
住院记录 }-- 病人

class 住院记录详情 {
    起始日期时间
    截止日期时间
}

住院记录详情 }-r- 住院记录
住院记录详情 -- 病床

class 住院部医生 {
}
住院部医生 --{ 住院记录

class 查床记录 {
    查房日期时间
}
查床记录 }-l- 住院部医生
查床记录 }-- 病人

'取药单、检查单
class 医嘱 {
    日期时间
}
class 检查单 {
    检查项
}
class 取药单 {
    药品
    数量
}
医嘱 }-- 查床记录
医嘱 -l- 取药单
医嘱 -r- 检查单

class 用药记录 {
    日期时间
}

用药记录 -- 管床护士
用药记录 -- 病人
用药记录 -- 医嘱

class 用药详情 {
    项目
    次数
}

@enduml


