@startuml

class 手术台

class 手术台申请记录 {
    申请人
    申请时间
    申请使用时间
}
手术台申请记录 -r- 手术台
手术台申请记录 -- 手术台使用记录

class 手术 {
    开始日期时间
    结束日期时间
}
手术 -l- 主刀医生
手术 -d- 病人

class 手术台使用记录 {
    手术日期时间
}
手术台使用记录 -- 手术
手术台使用记录 -r- 手术台

class 手术台使用明细 {
    物品
    数量
    单价
}
手术台使用明细 }-u- 手术台使用记录

@enduml