@startuml

class 取药单 {
    取药日期时间
    总价
}
取药单 }-u- 病人
取药单 }-u- 下单医生
取药单 }-l- 抓药医生

class 取药明细 {
    药品
    数量
    单价
}

取药明细 }-u- 取药单
取药明细 }-u- 药品

class 药品 {
}

class 药品库存 {
    库存
}
药品库存 -- 药品

class 入库记录 {
    入库日期时间
}

class 入库记录明细 {
    药品
    数量
}
入库记录明细 }-- 入库记录
入库记录明细 -- 药品

@enduml