@startuml

class 病人 {
    身份证号
    医保卡号
}

class 挂号记录 {
    id
    挂号日期时间
    取票开始时间
    取票截止时间
}

class 门诊医生 {
    id
    ...
}

class 科室 {
}

科室 --{ 门诊医生

挂号记录 }-u- 病人
挂号记录 }-r- 门诊医生
挂号记录 }-r- 科室

class 叫号凭证 {
    序号
}
叫号凭证 -u- 挂号记录

class 就诊记录 {
    就诊时间
}
就诊记录 }-- 门诊医生
就诊记录 }-- 病人
就诊记录 -d-{ 医嘱

'检查单、取药单、住院单
class 医嘱 {
}
医嘱 -- 检查单
医嘱 -- 取药单
医嘱 -- 住院单

class 检查单 {
    检查项
}

class 取药单 {
    药品
    数量
}

class 住院单 {

}


@enduml